# eBay Laptops & Notebooks - Modeling

### Loading Libraries

In [13]:
# Importing libraries and setting constants

# Libraries
import polars as pl

# Constants
RANDOM_SEED = 287
DATA_SOURCE_PATH = '../data/ebay_laptops_and_notebooks_cleansed.csv'

## Data Preparation

### Loading the dataset

In [9]:
df = pl.read_csv(DATA_SOURCE_PATH)
df.head(n=10).to_pandas()

,brand,currency,min_price,rating,five_star_scale_rating,ratings_count,condition_label,condition_description,seller_note,processor,...,processor_speed_unit,laptop_type,release_year,display_width,display_height,model,os,features,country_of_manufacturer,storage_type
0,chuwi,$,303.68,None,NaN,NaN,new,"A brand-new, unused, unopened, undamaged item ...",None,quad_core,...,GHz,laptop,2021.0,2160.0,1440.0,corebook_x,windows,"backlitkeyboard,built-inmicrophone,built-inwebcam",china,ssd
1,dell,$,399.99,None,NaN,NaN,very_good_refurbished,The item shows minimal wear and is backed by a...,“AAA PCs is a Microsoft Authorized Refurbisher...,intel_core_i7_8th_gen,...,GHz,laptop,2023.0,1920.0,1080.0,dell_latitude_7490,windows,"backlitkeyboard,bluetooth,built-inmicrophone,b...",unknown,ssd
2,dell,$,175.00,None,NaN,NaN,used,An item that has been used previously.\n Th...,"“Well kept, fully functional, includes battery...",intel_core_i5_6300u,...,GHz,laptop,2019.0,1920.0,1080.0,dell_latitude_e5470,windows,"10/100lancard,backlitkeyboard,bluetooth,built-...",china,ssd
3,hp,$,84.99,None,NaN,NaN,good_refurbished,The item shows moderate wear and is backed by ...,“1-Year Allstate warranty. The original HP cha...,intel_celeron_n,...,GHz,laptop,NaN,1366.0,768.0,hp_chromebook_11_g6,chrome,"bluetooth,built-inmicrophone,built-inwebcam,wi...",unknown,emmc
4,dell,$,101.22,None,NaN,NaN,good_refurbished,The item shows moderate wear and is backed by ...,“Laptops is tested & fully working with some s...,intel_core_i5_6th_gen,...,GHz,laptop,2015.0,1366.0,768.0,various_models,windows,"10/100lancard,built-inmicrophone,built-inwebca...",unknown,ssd
5,acer,$,49.99,4_5_out_of_5_stars,4.5,193.0,no_label,No description,None,intel_celeron,...,GHz,laptop,2017.0,1366.0,768.0,chromebook_c738tc44z,chrome,"touchscreen,bluetooth",unknown,ssd
6,hp,$,39.59,4_5_out_of_5_stars,4.5,23.0,no_label,No description,None,intel_celeron,...,GHz,laptop,2017.0,NaN,NaN,hp_chromebook_11_g5,chrome,"bluetooth,built-inwebcam",unknown,ssd
7,acer,$,34.99,5_out_of_5_stars,5.0,20.0,no_label,No description,None,intel_celeron_dual_core,...,GHz,laptop,NaN,NaN,NaN,chromebook_c7202848,chrome,None,unknown,unknown
8,dell,$,279.99,None,NaN,NaN,excellent_refurbished,"The item is in like-new condition, backed by a...",None,i7_7th,...,GHz,laptop,NaN,1920.0,1080.0,dell_latitude_7480,windows,wi-fi,unknown,ssd
9,hp,$,125.00,5_out_of_5_stars,5.0,5.0,no_label,No description,None,intel_core_i3_10th_gen,...,GHz,laptop,2020.0,1920.0,1080.0,samsung_chromebook_3,chrome,"touchscreen,bluetooth,built-inwebcam,wi-fi,bac...",unknown,emmc

### Dropping duplicates

In [12]:
df = df.unique()
df.head(n=10).to_pandas()

,brand,currency,min_price,rating,five_star_scale_rating,ratings_count,condition_label,condition_description,seller_note,processor,...,processor_speed_unit,laptop_type,release_year,display_width,display_height,model,os,features,country_of_manufacturer,storage_type
0,lenovo,$,51.00,None,NaN,NaN,used,An item that has been used previously.\n Th...,“Fully Tested and Fully working . Includes cha...,intel_celeron,...,GHz,laptop,2016.0,1366.0,768.0,lenovo_thinkpad_yoga_11e,chrome,touchscreen,unknown,ssd
1,lenovo,$,323.43,None,NaN,NaN,used,An item that has been used previously.\n Th...,None,intel_core_i5_7th_generation,...,GHz,laptop,NaN,NaN,NaN,t470s,windows,"touchid,10/100lancard,wi-fi,backlitkeyboard,bl...",unknown,unknown
2,gericom,$,21.98,None,NaN,NaN,for_parts_or_not_working,An item that does not function as intended and...,None,intel_pentium,...,unknown,unknown,NaN,NaN,NaN,None,unknown,None,unknown,unknown
3,dell,$,119.00,None,NaN,NaN,used,An item that has been used previously.\n Th...,“The computer has been professionally refurbis...,intel_core_i5_6300u_2.40ghz,...,GHz,laptop,NaN,NaN,NaN,latitude_e5470,windows,"webcam,sdslot",unknown,ssd
4,lenovo,$,358.51,None,NaN,NaN,used,An item that has been used previously.\n Th...,“Refurbished - Grade A”,core_i5,...,GHz,laptop,NaN,NaN,NaN,thinkpad_t490,unknown,None,unknown,unknown
5,unknown,$,1771.93,None,NaN,NaN,seller_refurbished,The item has been restored to working order by...,None,None,...,unknown,pc,NaN,NaN,NaN,None,unknown,None,unknown,unknown
6,unknown,$,97.89,None,NaN,NaN,used,An item that has been used previously.\n Th...,None,None,...,unknown,unknown,NaN,NaN,NaN,None,unknown,None,unknown,unknown
7,hp,$,36.99,None,NaN,NaN,used,An item that has been used previously.\n Th...,"“This item is fully functional. Overall, it is...",intel_celeron_n2840,...,unknown,unknown,NaN,NaN,NaN,None,unknown,None,unknown,unknown
8,panasonic,$,259.89,None,NaN,NaN,used,An item that has been used previously.\n Th...,None,core_i5_3437u,...,GHz,other,NaN,1920.0,1080.0,panasonic_toughpad_fzg1_mk1,windows,"widescreendisplay,integratedwebcamera",unknown,unknown
9,dell,$,50.00,None,NaN,NaN,used,An item that has been used previously.\n Th...,“Used laptop. Passes all diagnostics test wit...,intel_core_i3_4th_gen,...,GHz,laptop,NaN,1366.0,768.0,dell_latitude_3540,windows,"built-inwebcam,wi-fi",unknown,ssd

## Exploratory Data Analysis

In [ ]:
## TODO : Exploratory Data Analysis

## Feature Engineering

In [ ]:
## TODO : Feature Engineering

## Machine Learning

In [19]:
## TODO : Machine Learning

## Hyperparameter Tuning

In [ ]:
## TODO : Hyperparameter Tuning

## Explainable AI - SHAP

In [ ]:
## TODO : Explainable AI - SHAP