# eBay Laptops & Notebooks - Data Cleansing

The following dataset contains information about laptops and notebooks, by web scraping the popular e-commerce website
**eBay**.

The dataset contains information about the laptop prices (possible variable of interest), brand, ratings, condition, as well as hardware information (processor, screen size, ram, etc).

<div style="text-align: center;">
<img src="../assets/logos/ebay.png" width="250"/>
</div>

In [8]:
# Importing libraries
import polars as pl

In [6]:
# Loading the dataset
df = pl.read_csv('../data/ebay_laptops_and_notebooks.csv')

# Top 10 rows from the dataframe
df.head(n=10)

shape: (10, 23)
╭───────┬────────────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────╮
│ Brand ┆ Price      ┆ Rating     ┆ Ratings    ┆ … ┆ Features  ┆ Hard      ┆ Country   ┆ Storage   │
│ ---   ┆ ---        ┆ ---        ┆ Count      ┆   ┆ ---       ┆ Drive     ┆ Region Of ┆ Type      │
│ str   ┆ str        ┆ str        ┆ ---        ┆   ┆ str       ┆ Capacity  ┆ Manufactu ┆ ---       │
│       ┆            ┆            ┆ i64        ┆   ┆           ┆ ---       ┆ re        ┆ str       │
│       ┆            ┆            ┆            ┆   ┆           ┆ str       ┆ ---       ┆           │
│       ┆            ┆            ┆            ┆   ┆           ┆           ┆ str       ┆           │
╞═══════╪════════════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ CHUWI ┆ $303.68    ┆ null       ┆ null       ┆ … ┆ Backlit   ┆ 512 GB    ┆ China     ┆ SSD       │
│       ┆            ┆            ┆            ┆   ┆ Keyboard, ┆ SSD       ┆           ┆ (Solid    │
│       ┆            ┆            ┆            ┆   ┆ Built-in  ┆           ┆           ┆ State     │
│       ┆            ┆            ┆            ┆   ┆ Mi…       ┆           ┆           ┆ Drive)    │
│ Dell  ┆ $399.99 to ┆ null       ┆ null       ┆ … ┆ Backlit   ┆ 2 TB      ┆ null      ┆ SSD       │
│       ┆ $634.99    ┆            ┆            ┆   ┆ Keyboard, ┆           ┆           ┆ (Solid    │
│       ┆            ┆            ┆            ┆   ┆ Bluetooth ┆           ┆           ┆ State     │
│       ┆            ┆            ┆            ┆   ┆ , B…      ┆           ┆           ┆ Drive)    │
│ Dell  ┆ $175.00    ┆ null       ┆ null       ┆ … ┆ 10/100    ┆ 500 GB    ┆ China     ┆ SSD       │
│       ┆            ┆            ┆            ┆   ┆ LAN Card, ┆           ┆           ┆ (Solid    │
│       ┆            ┆            ┆            ┆   ┆ Backlit   ┆           ┆           ┆ State     │
│       ┆            ┆            ┆            ┆   ┆ Keybo…    ┆           ┆           ┆ Drive)    │
│ HP    ┆ $84.99     ┆ null       ┆ null       ┆ … ┆ Bluetooth ┆ 16 GB     ┆ null      ┆ eMMC      │
│       ┆            ┆            ┆            ┆   ┆ ,         ┆           ┆           ┆           │
│       ┆            ┆            ┆            ┆   ┆ Built-in  ┆           ┆           ┆           │
│       ┆            ┆            ┆            ┆   ┆ Microphon ┆           ┆           ┆           │
│       ┆            ┆            ┆            ┆   ┆ e…        ┆           ┆           ┆           │
│ Dell  ┆ $101.22    ┆ null       ┆ null       ┆ … ┆ 10/100    ┆ NO HDD    ┆ null      ┆ SSD       │
│       ┆            ┆            ┆            ┆   ┆ LAN Card, ┆           ┆           ┆ (Solid    │
│       ┆            ┆            ┆            ┆   ┆ Built-in  ┆           ┆           ┆ State     │
│       ┆            ┆            ┆            ┆   ┆ Micr…     ┆           ┆           ┆ Drive)    │
│ Acer  ┆ $49.99     ┆ 4.5 out of ┆ 193        ┆ … ┆ Touchscre ┆ null      ┆ null      ┆ SSD       │
│       ┆            ┆ 5 stars    ┆            ┆   ┆ en,       ┆           ┆           ┆ (Solid    │
│       ┆            ┆            ┆            ┆   ┆ Bluetooth ┆           ┆           ┆ State     │
│       ┆            ┆            ┆            ┆   ┆           ┆           ┆           ┆ Drive)    │
│ HP    ┆ $39.59     ┆ 4.5 out of ┆ 23         ┆ … ┆ Bluetooth ┆ 16 GB     ┆ null      ┆ SSD       │
│       ┆            ┆ 5 stars    ┆            ┆   ┆ ,         ┆           ┆           ┆ (Solid    │
│       ┆            ┆            ┆            ┆   ┆ Built-in  ┆           ┆           ┆ State     │
│       ┆            ┆            ┆            ┆   ┆ Webcam    ┆           ┆           ┆ Drive)    │
│ Acer  ┆ $34.99     ┆ 5 out of 5 ┆ 20         ┆ … ┆ null      ┆ 16GB      ┆ null      ┆ null      │
│       ┆            ┆ stars      ┆            ┆   ┆           ┆           ┆           ┆           │
│ Dell  ┆ $279.99    ┆ null       ┆ null       ┆ … ┆ Wi-Fi     ┆ 512 GB    ┆ null      ┆ SSD       │
│       ┆            ┆            ┆            ┆   ┆           ┆           ┆           ┆ (Solid    │
│       ┆            ┆            ┆            ┆   ┆           ┆           ┆           ┆ State     │
│       ┆            ┆            ┆            ┆   ┆           ┆           ┆           ┆ Drive)    │
│ HP    ┆ $125.00    ┆ 5 out of 5 ┆ 5          ┆ … ┆ Touchscre ┆ null      ┆ null      ┆ eMMC      │
│       ┆            ┆ stars      ┆            ┆   ┆ en, Bluet ┆           ┆           ┆           │
│       ┆            ┆            ┆            ┆   ┆ ooth,     ┆           ┆           ┆           │
│       ┆            ┆            ┆            ┆   ┆ Built-…   ┆           ┆           ┆           │
╰───────┴────────────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────╯

Observations:

* `Price` variable contains information about the price itself, but also the currency. Also, some prices are in a range format, such as `$399.99 to $634.99` which needs to be handled before converting `Price` into a numerical variable.
* **Several** columns are being treated as `String` (such as `Price`), which might not be adequate.
* **Several** columns have **missing values**, which needs to be treated during further data preprocessing.

In [6]:
# Summary statistics
df.describe()

shape: (9, 24)
┌────────────┬───────┬────────────┬────────────┬───┬──────────┬────────────┬───────────┬───────────┐
│ statistic  ┆ Brand ┆ Price      ┆ Rating     ┆ … ┆ Features ┆ Hard Drive ┆ Country   ┆ Storage   │
│ ---        ┆ ---   ┆ ---        ┆ ---        ┆   ┆ ---      ┆ Capacity   ┆ Region Of ┆ Type      │
│ str        ┆ str   ┆ str        ┆ str        ┆   ┆ str      ┆ ---        ┆ Manufactu ┆ ---       │
│            ┆       ┆            ┆            ┆   ┆          ┆ str        ┆ rer       ┆ str       │
│            ┆       ┆            ┆            ┆   ┆          ┆            ┆ ---       ┆           │
│            ┆       ┆            ┆            ┆   ┆          ┆            ┆ str       ┆           │
╞════════════╪═══════╪════════════╪════════════╪═══╪══════════╪════════════╪═══════════╪═══════════╡
│ count      ┆ 4024  ┆ 6620       ┆ 286        ┆ … ┆ 2505     ┆ 2332       ┆ 203       ┆ 2388      │
│ null_count ┆ 2596  ┆ 0          ┆ 6334       ┆ … ┆ 4115     ┆ 4288       ┆ 6417      ┆ 4232      │
│ mean       ┆ null  ┆ null       ┆ null       ┆ … ┆ null     ┆ null       ┆ null      ┆ null      │
│ std        ┆ null  ┆ null       ┆ null       ┆ … ┆ null     ┆ null       ┆ null      ┆ null      │
│ min        ┆ ?     ┆ $1,002.67  ┆ 1 out of 5 ┆ … ┆ .        ┆ .          ┆ Australia ┆ .         │
│            ┆       ┆            ┆ stars      ┆   ┆          ┆            ┆           ┆           │
│ 25%        ┆ null  ┆ null       ┆ null       ┆ … ┆ null     ┆ null       ┆ null      ┆ null      │
│ 50%        ┆ null  ┆ null       ┆ null       ┆ … ┆ null     ┆ null       ┆ null      ┆ null      │
│ 75%        ┆ null  ┆ null       ┆ null       ┆ … ┆ null     ┆ null       ┆ null      ┆ null      │
│ max        ┆ xnote ┆ $999.95    ┆ 5 out of 5 ┆ … ┆ dvd      ┆ up to 1 TB ┆ Unknown   ┆ ssd       │
│            ┆       ┆            ┆ stars      ┆   ┆          ┆            ┆           ┆           │
└────────────┴───────┴────────────┴────────────┴───┴──────────┴────────────┴───────────┴───────────┘

In [5]:
# Data Types
pl.DataFrame(data={
    'column': df.columns,
    'dtype': df.dtypes
})

shape: (23, 2)
┌───────────────────────────────┬────────┐
│ column                        ┆ dtype  │
│ ---                           ┆ ---    │
│ str                           ┆ object │
╞═══════════════════════════════╪════════╡
│ Brand                         ┆ String │
│ Price                         ┆ String │
│ Rating                        ┆ String │
│ Ratings Count                 ┆ Int64  │
│ Condition                     ┆ String │
│ …                             ┆ …      │
│ OS                            ┆ String │
│ Features                      ┆ String │
│ Hard Drive Capacity           ┆ String │
│ Country Region Of Manufacture ┆ String │
│ Storage Type                  ┆ String │
└───────────────────────────────┴────────┘

As aforementioned, many variables are currently being treated as `String`. In the case of `Price`, it is a numerical variable which is being incorrectly read as a categorical variable.

## Data Preparation

In [10]:
# Renaming columns: replacing blank spaces for underscores and lowercasing columns
df = df.rename({col: col.lower().replace(' ', '_') for col in df.columns})
print(df.columns)

['brand', 'price', 'rating', 'ratings_count', 'condition', 'seller_note', 'processor', 'screen_size', 'manufacturer_color', 'color', 'ram_size', 'ssd_capacity', 'gpu', 'processor_speed', 'type', 'release_year', 'maximum_resolution', 'model', 'os', 'features', 'hard_drive_capacity', 'country_region_of_manufacture', 'storage_type']

In [10]:
# Nulls per each column in the dataset
df.null_count().unpivot(
    variable_name='variable',
    value_name='null_count',
).sort(
    by='null_count', descending=True,
).with_columns(
    (pl.col('null_count') / len(df)).round(decimals=2).alias('null_proportion'),
)

shape: (23, 3)
╭───────────────────────────────┬────────────┬─────────────────╮
│ variable                      ┆ null_count ┆ null_proportion │
│ ---                           ┆ ---        ┆ ---             │
│ str                           ┆ u32        ┆ f64             │
╞═══════════════════════════════╪════════════╪═════════════════╡
│ Manufacturer Color            ┆ 6435       ┆ 0.97            │
│ Country Region Of Manufacture ┆ 6417       ┆ 0.97            │
│ Rating                        ┆ 6334       ┆ 0.96            │
│ Ratings Count                 ┆ 6334       ┆ 0.96            │
│ Release Year                  ┆ 5833       ┆ 0.88            │
│ …                             ┆ …          ┆ …               │
│ Processor                     ┆ 2783       ┆ 0.42            │
│ Screen Size                   ┆ 2730       ┆ 0.41            │
│ Brand                         ┆ 2596       ┆ 0.39            │
│ Condition                     ┆ 616        ┆ 0.09            │
│ Price                         ┆ 0          ┆ 0.0             │
╰───────────────────────────────┴────────────┴─────────────────╯

Nulls:
-
- Extremely high percentage of nulls for columns such as `country_region_of_manufacturer`, `ratings_count` or `release_year` which are very features one would expect to be related with a laptop's price.
- `Price` column has no null values.